name: Android CI Quality Check

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test_and_lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # O 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Permessi di esecuzione Gradle
        run: chmod +x gradlew

      # 1. Esegue Detekt per il controllo qualità
      - name: Run Detekt
        run: ./gradlew detekt

      # 2. Esegue i Test Unitari
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      # 3. (Opzionale) Esegue Android Lint
      - name: Run Android Lint
        run: ./gradlew lintDebug